name: Build

on: push

jobs:
  install_dependencies:
    name: Installing dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install

      - name: Zipping node_modules folder
        run: zip -r node_modules.zip node_modules

      - name: Uploading node_modules folder as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: node-modules-artifact
          path: node_modules.zip

  lint:
    name: Test
    runs-on: ubuntu-latest
    needs:
      - install_dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download node_modules folder as an artifact
        uses: actions/download-artifact@v2
        with:
          name: node-modules-artifact

      - name: Unzipping node_modules.zip
        run: unzip node_modules.zip -d node_modules

      - name: Test
        run: yarn run test

  build:
    name: Build project
    runs-on: ubuntu-latest
    needs:
      - lint
      - install_dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download node_modules folder as an artifact
        uses: actions/download-artifact@v2
        with:
          name: node-modules-artifact

      - name: Unzipping node_modules.zip
        run: unzip node_modules.zip -d node_modules

      - name: Build project
        run: yarn build