name: Build

on: push

jobs:
  install_dependencies:
    name: Installing dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install

  build:
    name: Build project
    runs-on: ubuntu-latest
    needs:
      - install_dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install

      - name: Build project
        run: yarn build

  upload_map_files_to_sentry:
    name: Upload .map files to Sentry
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Install Sentry CLI
        run: yarn add @sentry/cli
