name: Build

on: push

jobs:
  install_dependencies:
    name: Installing dependencies
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup NodeJS v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install packages
        run: yarn install

  build:
    name: Build project
    runs-on: ubuntu-20.04
    needs:
      - install_dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup NodeJS v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install packages
        run: yarn install

      - name: Build project
        run: yarn build

      - name: List the files
        run: ls -la

      - name: List the files inside the build folder
        run: cd ./build && ls -la

      - name: Caching build folder
        uses: actions/cache@v1
        with:
          path: build
          key: ${{ runner.os }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

  create_sentry_release:
    name: Creating Sentry release
    runs-on: ubuntu-20.04
    needs:
      - build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restoring cached build folder
        uses: actions/cache@v1
        with:
          path: build
          key: ${{ runner.os }}-build-${{ hashFiles('**/yarn.lock') }}

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          ignore_empty: true
          environment: production
          sourcemaps: './build/static/js'
          version: 'v1.0.1'