name: Build

on: [push, pull_request_target]

env:
  IS_UPSTREAM: ${{ github.repository == 'BumbuKhan/github-actions' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    # This job runs only on `BumbuKhan/github-actions` repository and will always be skipped on forks
    if: ${{ env.IS_UPSTREAM == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: echo IS_UPSTREAM
        run: echo $IS_UPSTREAM

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install

      - name: Build
        run: yarn run build
